### ISSUE TITLE
Universal Interface functions get overwritten by OpenP

### ISSUE THREAD

**Issue by Nathan1852** [RSDuck/RandomPeripherals#4]
Could you add the @Ignore annotation to the Universal Interface?

https://github.com/OpenMods/OpenPeripheral/blob/master/src/main/java/openperipheral/api/peripheral/Ignore.java

**Comment by RSDuck** [comment]
Sure, the next version(which will be released probably next week) will include that change.
One question left: what exactly prevents the Ignore annotation, the file says Open Peripherals will skip the peripheral generation, but what means peripheral generation, do I need to add this to all peripheral blocks if I add more?

**Comment by Nathan1852** [comment]
I think this prevents your methods from being overwritten by OpenP. I had the problem before that I only could access the OpenP methods and not yours.
Also, could you make it possible to wrap a peripheral on the side of the interface? So that you have an interface wrapped and next to it a chest for example. You would have a function like 'inerface.wrap(side)' which would return the peripheral on the specified side. So you would only have to wrap the interface and not the chest

**Comment by RSDuck** [comment]
I tried the latest stable and the latest snapshot of OpenPeripherals within my Mod Dev Environment and everything works as it should do, so I don't see any reason why I should add the Ignore Annotation.

I keep the issue open, maybe there is a difference inside of a non Mod Dev Environment

**Comment by Nathan1852** [comment]
I tried it with the latest OpenPeripherals snapshot and the functions got overwritten.
I let CC write them to a file, these are the functions it got:

1 : resetSides
2 : setSide
3 : condenseItems
4 : expandStack
5 : decrSide
6 : swapStacks
7 : destroyStack
8 : getNumConfig
9 : pushItemIntoSlot
10 : getAdvancedMethodsData
11 : getMaxEnergyStored
12 : getAllStacks
13 : pushItem
14 : getInventoryName
15 : pullItem
16 : getEnergyStored
17 : getStackInSlot
18 : allowYAxisFacing
19 : listSources
20 : incrSide
21 : getTankInfo
22 : getInventorySize
23 : rotateBlock
24 : pullItemIntoSlot
25 : doc
26 : listMethods
27 : getFacing
28 : setFacing

listMethods and doc are OpenP functions, I know that. I think I have some mods which use OpenPs Api for peripherals, so it could be that it isn't OpenP alone, but the OpenP Api, which (in theory) should look for the @Ignore Annotation.

**Comment by RSDuck** [comment]
Ich habe jetzt nochmal alles im normal zustand mit nicht dekompilierten Minecraft ect. ausprobiert. 
Mit der neusten Version von Random Peripherals scheint es kein Problem zu geben

**Comment by Nathan1852** [comment]
I did some testing and Vexatos found out what the problem was in [Issue 147](https://github.com/asiekierka/Computronics/issues/147) of Computronics
