### ISSUE TITLE
[Suggestion] More commands for the Universal Interface

### ISSUE THREAD

**Issue by Nathan1852** [RSDuck/RandomPeripherals#5]
I had a few Ideas for the Universal Interface which would made it even more usefull. It would be nice if you could take a look at them and at least say if they are possible or not ;)

1. Get Info for the Tank inside
It would be very usefull if one could get Infos about the fluid in the internal Tank. 
Infos such as: how much is there, what kind of fluid...

2. Option to Output/(input?) fluids seperately and with an amount
With a function like 'outputFluid(side, amountInMillibuckets)'
It could be quite usefull to fill machines with the right amount of fluid they need

3. Option to Output/Input Energy seperately and with an amount
With a function like 'outputEnergy(side, energyAmountInRF)'
It could be usefull to set the Input/Output Amount of Energy per side, not completely for the block

4. Wrap peripherals next to the Universal Interface
It would be incredibly usefull to have the possibility to wrap Inventories next to the Universal Interface.
A function like 'wrap(side)', which just wraps the peripheral on the specified side just as if a computer was next to it. It would be very usefull to make builds like the one down below possible:
![2015-07-19_21 39 50](https://cloud.githubusercontent.com/assets/5282863/8767498/341e7d0c-2e5f-11e5-832b-944eca19a5b8.png)
![2015-07-19_21 39 57](https://cloud.githubusercontent.com/assets/5282863/8767505/4c219bd2-2e5f-11e5-8d41-c81bbfb6f7f2.png)

So that one can get the amount of Items or Energy or Fluids that is in the Inventory/Machine next to the Interface.
If you have any questions at how one of the suggestions would work, feel free to ask

**Comment by RSDuck** [comment]
The input/output control for every side is just a matter of some variables that should be replaced with arrays, so no problem. 
The peripheral thing is a bit more difficult, because there is no way of the normal ComputerCraft API to get an peripheral on an specific position, but I just decompiled ComputerCraft and it wasn't difficult to find the right function which can be called with Reflection to get the peripheral at an specific position.

So both things are not too hard to implement

**Comment by Nathan1852** [comment]
It would be brilliant if you could make all those work. This would allow me (and anyone else) to create their own AE network with computers. Do you think they make it in the Update you have planed soon?

**Comment by RSDuck** [comment]
Yes, both things will probably be in the update, it's nothing complicated

**Comment by Nathan1852** [comment]
Any news on the update?

**Comment by RSDuck** [comment]
It took a litte bit longer(The hologram projector rendering needed some time).
Now everything and more except the wrapping of the other peripherals from an UI is implemented, but that has not to do anything with graphics, so it shouldn't be that problem.

The update will, if no major bug appears on the last tests, released today or tommorow.

But for now I will go to bed, here in Germany it's 1 AM

**Comment by Nathan1852** [comment]
Thanks for the answer. I hope that no major bugs appear. 

Nice to know that you are german, too ;) We could have had this whole conversation in german

**Comment by RSDuck** [comment]
So, alles ist fertig, ich führe gerade noch die letzten Tests durch bevor ich die neue Version hochlade.

Eigentlich gilt es als unprofessionell sich nicht auf Englisch zu unterhalten, ich mache die das hier sowieso gleich zu wenn ich den Commit mache.

**Comment by RSDuck** [comment]
Alles fertig!
