### ISSUE TITLE
Crash upon starting up server

### ISSUE THREAD

**Issue by Lokilotus** [RSDuck/RandomPeripherals#8]
Full Crashlog: http://pastebin.com/FkJnxAF6

Hopefully this gets fixed soon, as we kinda need this on our server so we can read NBT data using ComputerCraft- as part of our ComputerCraft Challenge (i.e. do EVERYTHING with CC and some addons) :P

Thanks,

-Loki

**Comment by RSDuck** [comment]
I fixed the issue in the last commit, but there are some other major bugs that need to be fixed(I nothing too complicated, I'm just to lazy to fix them right now).

The bug fix will be released probably today or tomorrow
